# SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

openapi: 3.0.3
info:
  title: Zextras Carbonio Workstream Collaboration CE Meeting Api
  description: Zextras Carbonio Workstream Collaboration CE Meeting HTTP APIs definition.
  version: 0.3.2
  contact:
    email: smokybeans@zextras.com
servers:
  - url: http://localhost:10000
tags:
  - name: Meetings
paths:
  /meetings:
    get:
      tags:
        - Meetings
      summary: Retrieves a list of every meeting the user has access to
      operationId: listMeeting
      responses:
        200:
          $ref: '#/components/responses/200ListMeetingResponse'
  /meetings/{meetingId}:
    get:
      tags:
        - Meetings
      summary: Retrieves the requested meeting
      operationId: getMeeting
      parameters:
        - $ref: '#/components/parameters/pathMeetingId'
      responses:
        200:
          $ref: '#/components/responses/200GetMeetingResponse'
        401:
          $ref: '#/components/responses/401UnauthorizedResponse'
        403:
          $ref: '#/components/responses/403ForbiddenResponse'
        404:
          $ref: '#/components/responses/404NotFoundResponse'
    delete:
      tags:
        - Meetings
      summary: Deletes the requested meeting
      operationId: deleteMeeting
      parameters:
        - $ref: '#/components/parameters/pathMeetingId'
      responses:
        204:
          $ref: '#/components/responses/204DeleteMeetingResponse'
        401:
          $ref: '#/components/responses/401UnauthorizedResponse'
        403:
          $ref: '#/components/responses/403ForbiddenResponse'
        404:
          $ref: '#/components/responses/404NotFoundResponse'
  /meetings/{meetingId}/join:
    put:
      tags:
        - Meetings
      summary: Adds the current user to the specified meeting
      operationId: joinMeeting
      parameters:
        - $ref: '#/components/parameters/pathMeetingId'
      requestBody:
        $ref: '#/components/requestBodies/JoinMeetingRequest'
      responses:
        204:
          $ref: '#/components/responses/204JoinMeetingResponse'
        401:
          $ref: '#/components/responses/401UnauthorizedResponse'
        403:
          $ref: '#/components/responses/403ForbiddenResponse'
        404:
          $ref: '#/components/responses/404NotFoundResponse'
  /meetings/{meetingId}/leave:
    put:
      tags:
        - Meetings
      summary: Remove the current user to the specified meeting
      operationId: leaveMeeting
      parameters:
        - $ref: '#/components/parameters/pathMeetingId'
      responses:
        204:
          $ref: '#/components/responses/204LeaveMeetingResponse'
        401:
          $ref: '#/components/responses/401UnauthorizedResponse'
        403:
          $ref: '#/components/responses/403ForbiddenResponse'
        404:
          $ref: '#/components/responses/404NotFoundResponse'
  /meetings/{meetingId}/sessions/{sessionId}/video:
    put:
      tags:
        - Meetings
      summary: Update video stream status for the current session
      operationId: updateVideoStream
      parameters:
        - $ref: '#/components/parameters/pathMeetingId'
        - $ref: '#/components/parameters/pathSessionId'
      requestBody:
        $ref: '#/components/requestBodies/UpdateVideoStreamRequest'
      responses:
        204:
          $ref: '#/components/responses/204VideoStreamResponse'
        401:
          $ref: '#/components/responses/401UnauthorizedResponse'
        403:
          $ref: '#/components/responses/403ForbiddenResponse'
        404:
          $ref: '#/components/responses/404NotFoundResponse'
  /meetings/{meetingId}/sessions/{sessionId}/video/offer:
    put:
      tags:
        - Meetings
      summary: Start WebRTC negotiation for video stream for the current session
      operationId: offerRtcVideoStream
      parameters:
        - $ref: '#/components/parameters/pathMeetingId'
        - $ref: '#/components/parameters/pathSessionId'
      requestBody:
        $ref: '#/components/requestBodies/RtcMediaStreamRequest'
      responses:
        204:
          $ref: '#/components/responses/204OfferVideoStreamResponse'
        401:
          $ref: '#/components/responses/401UnauthorizedResponse'
        403:
          $ref: '#/components/responses/403ForbiddenResponse'
        404:
          $ref: '#/components/responses/404NotFoundResponse'
  /meetings/{meetingId}/sessions/{sessionId}/video/answer:
    put:
      tags:
        - Meetings
      summary: Complete WebRTC negotiation for media streams for the current session
      operationId: answerRtcMediaStream
      parameters:
        - $ref: '#/components/parameters/pathMeetingId'
        - $ref: '#/components/parameters/pathSessionId'
      requestBody:
        $ref: '#/components/requestBodies/RtcMediaStreamRequest'
      responses:
        204:
          $ref: '#/components/responses/204AnswerMediaStreamResponse'
        401:
          $ref: '#/components/responses/401UnauthorizedResponse'
        403:
          $ref: '#/components/responses/403ForbiddenResponse'
        404:
          $ref: '#/components/responses/404NotFoundResponse'
  /meetings/{meetingId}/sessions/{sessionId}/video/subscribe:
    put:
      tags:
        - Meetings
      summary: Update subscriptions of the current session to the desired media streams
      operationId: updateSubscriptionsMediaStream
      parameters:
        - $ref: '#/components/parameters/pathMeetingId'
        - $ref: '#/components/parameters/pathSessionId'
      requestBody:
        $ref: '#/components/requestBodies/UpdateMediaStreamSubscriptionsRequest'
      responses:
        204:
          $ref: '#/components/responses/204SubscribeVideoStreamResponse'
        401:
          $ref: '#/components/responses/401UnauthorizedResponse'
        403:
          $ref: '#/components/responses/403ForbiddenResponse'
        404:
          $ref: '#/components/responses/404NotFoundResponse'
  /meetings/{meetingId}/sessions/{sessionId}/audio:
    put:
      tags:
        - Meetings
      summary: Update audio stream status for the current session
      operationId: updateAudioStream
      parameters:
        - $ref: '#/components/parameters/pathMeetingId'
        - $ref: '#/components/parameters/pathSessionId'
      requestBody:
        $ref: '#/components/requestBodies/UpdateAudioStreamRequest'
      responses:
        204:
          $ref: '#/components/responses/204AudioStreamResponse'
        401:
          $ref: '#/components/responses/401UnauthorizedResponse'
        403:
          $ref: '#/components/responses/403ForbiddenResponse'
        404:
          $ref: '#/components/responses/404NotFoundResponse'
  /meetings/{meetingId}/sessions/{sessionId}/audio/offer:
    put:
      tags:
        - Meetings
      summary: Start WebRTC negotiation for audio stream for the current session
      operationId: offerRtcAudioStream
      parameters:
        - $ref: '#/components/parameters/pathMeetingId'
        - $ref: '#/components/parameters/pathSessionId'
      requestBody:
        $ref: '#/components/requestBodies/RtcMediaStreamRequest'
      responses:
        204:
          $ref: '#/components/responses/204OfferAudioStreamResponse'
        401:
          $ref: '#/components/responses/401UnauthorizedResponse'
        403:
          $ref: '#/components/responses/403ForbiddenResponse'
        404:
          $ref: '#/components/responses/404NotFoundResponse'
  /meetings/{meetingId}/sessions/{sessionId}/screen:
    put:
      tags:
        - Meetings
      summary: Update screen stream status for the current session
      operationId: UpdateScreenStream
      parameters:
        - $ref: '#/components/parameters/pathMeetingId'
        - $ref: '#/components/parameters/pathSessionId'
      requestBody:
        $ref: '#/components/requestBodies/UpdateScreenStreamRequest'
      responses:
        204:
          $ref: '#/components/responses/204ScreenStreamResponse'
        401:
          $ref: '#/components/responses/401UnauthorizedResponse'
        403:
          $ref: '#/components/responses/403ForbiddenResponse'
        404:
          $ref: '#/components/responses/404NotFoundResponse'
  /meetings/{meetingId}/sessions/{sessionId}/screen/offer:
    put:
      tags:
        - Meetings
      summary: Start WebRTC negotiation for screen stream for the current session
      operationId: offerRtcScreenStream
      parameters:
        - $ref: '#/components/parameters/pathMeetingId'
        - $ref: '#/components/parameters/pathSessionId'
      requestBody:
        $ref: '#/components/requestBodies/RtcMediaStreamRequest'
      responses:
        204:
          $ref: '#/components/responses/204OfferScreenStreamResponse'
        401:
          $ref: '#/components/responses/401UnauthorizedResponse'
        403:
          $ref: '#/components/responses/403ForbiddenResponse'
        404:
          $ref: '#/components/responses/404NotFoundResponse'

components:
  parameters:
    pathMeetingId:
      in: path
      name: meetingId
      description: meeting identifier
      schema:
        type: string
        format: uuid
      required: true
      allowEmptyValue: false
    pathSessionId:
      in: path
      name: sessionId
      description: session identifier
      schema:
        type: string
      required: true
      allowEmptyValue: false

  requestBodies:
    JoinMeetingRequest:
      description: user request containing its streams settings to join a meeting
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/JoinSettings'
    UpdateVideoStreamRequest:
      description: user request to update a meeting stream status
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/VideoStreamSettings'
    UpdateAudioStreamRequest:
      description: user request to update a meeting stream status
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AudioStreamSettings'
    RtcMediaStreamRequest:
      description: user request to send a rtc session description related to media stream for WebRTC negotiation
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RtcSessionDescription'
    UpdateMediaStreamSubscriptionsRequest:
      description: user request to update subscriptions to the desired media stream
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SubscriptionUpdates'
    UpdateScreenStreamRequest:
      description: user request to update a meeting stream status
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ScreenStreamSettings'

  responses:
    200ListMeetingResponse:
      description: List of every meeting that the user has access to
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Meeting'
    200GetMeetingResponse:
      description: Gets the requested meeting data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Meeting'
    201CreateMeetingResponse:
      description: Meeting was created successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Meeting'
    204DeleteMeetingResponse:
      description: The meeting was deleted successfully
    204JoinMeetingResponse:
      description: The user joined the meeting successfully
    204LeaveMeetingResponse:
      description: The user exited the meeting successfully
    204AudioStreamResponse:
      description: The status of audio stream changed successfully
    204OfferAudioStreamResponse:
      description: The offer related to the audio stream has been processed and sent successfully
    204VideoStreamResponse:
      description: The status of video stream changed successfully
    204OfferVideoStreamResponse:
      description: The offer related to the video stream has been processed and sent successfully
    204AnswerMediaStreamResponse:
      description: The answer related to the media stream has been processed and sent successfully
    204SubscribeVideoStreamResponse:
      description: The user subscribed to media streams successfully
    204ScreenStreamResponse:
      description: The status of screen stream changed successfully
    204OfferScreenStreamResponse:
      description: The offer related to the screen stream has been processed successfully

    400BadRequestResponse:
      description: The request had wrong or missing parameters
    401UnauthorizedResponse:
      description: User not authorized
    403ForbiddenResponse:
      description: The requester could not access the resource
    404NotFoundResponse:
      description: The requested resource was not found
    409Conflict:
      description: The request conflict with the current state

  schemas:
    Participant:
      type: object
      description: Meeting participant data
      properties:
        userId:
          type: string
          format: uuid
          readOnly: true
          description: user identifier
        sessionId:
          type: string
          readOnly: true
          description: VideoServer session id
        audioStreamEnabled:
          type: boolean
          readOnly: true
          description: indicates the audio stream status
        videoStreamEnabled:
          type: boolean
          readOnly: true
          description: indicates the video stream status
        screenStreamEnabled:
          type: boolean
          readOnly: true
          description: indicates the screen stream status
    Meeting:
      type: object
      description: Meeting data
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          description: meesting identifier
        roomId:
          type: string
          format: uuid
          readOnly: true
          description: meesting identifier
        participants:
          type: array
          items:
            $ref: '#/components/schemas/Participant'
        createdAt:
          type: string
          format: date-time
          readOnly: true
          description: entity creation date
    JoinSettings:
      type: object
      description: user's streams settings to join a meeting
      properties:
        audioStreamEnabled:
          type: boolean
          default: false
          description: indicates the audio stream status to join the meeting
        videoStreamEnabled:
          type: boolean
          default: false
          description: indicates the video stream status to join the meeting
      required: [ audioStreamEnabled, videoStreamEnabled ]
    VideoStreamSettings:
      type: object
      description: settings to apply on user's video stream
      properties:
        enabled:
          type: boolean
          description: indicates the status to change the video stream to
      required: [ enabled ]
    AudioStreamSettings:
      type: object
      description: settings to apply on user's audio stream
      properties:
        enabled:
          type: boolean
          description: indicates the status to change the audio stream to
      required: [ enabled ]
    RtcSessionDescription:
      type: object
      description: contains description type and sdp descriptor needed for a media stream to perform WebRTC negotiation
      properties:
        type:
          type: string
          description: indicates the description type
          enum:
            - offer
            - answer
        sdp:
          type: string
          description: indicates the descriptor of the session
      required: [ type, sdp ]
    SubscriptionUpdates:
      type: object
      description: subscriptions updates related to media streams
      properties:
        subscribe:
          type: array
          description: indicates the media streams which user wants to subscribe to
          items:
            $ref: '#/components/schemas/MediaStream'
        unsubscribe:
          type: array
          description: indicates the media streams which user wants to unsubscribe to
          items:
            $ref: '#/components/schemas/MediaStream'
      required: [ subscribe, unsubscribe ]
    MediaStream:
      type: object
      description: representation of meeting media stream
      properties:
        session_id:
          type: string
          description: session identifier which owns the related media stream
        type:
          type: string
          description: indicates the media stream type
          enum:
            - video
            - screen
      required: [ session_id, type ]

    ScreenStreamSettings:
      type: object
      description: settings to apply on user's screen stream
      properties:
        enabled:
          type: boolean
          description: indicates the status to change the screen stream to
      required: [ enabled ]