# SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carbonio-ws-collaboration-ce
  title: Carbonio Workstream Collaboration CE service
  description: |
    Service containing the business logic of the Workstream Collaboration application.
    It allows to chat or video-call with other users.
  tags:
    - java
    - backend
  links:
    - url: https://github.com/Zextras/carbonio-ws-collaboration-ce/blob/main/README.md
      title: README
spec:
  type: service
  lifecycle: production
  owner: smoky-beans
  providesApis:
    - carbonio-ws-collaboration-ce-rest-api
  dependsOn:
    - component:carbonio-ws-collaboration-db
    - component:carbonio-message-dispatcher
    - component:carbonio-message-broker
    - component:carbonio-user-management
    - component:carbonio-storages-ce
    - component:carbonio-preview-ce
    - component:carbonio-videoserver

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: carbonio-ws-collaboration-ce-rest-api
  title: Carbonio Workstream Collaboration CE REST APIs
  description: Carbonio Workstream Collaboration Community Edition REST APIs.
  tags:
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: smoky-beans
  definition:
    $text: https://github.com/Zextras/carbonio-ws-collaboration-ce/blob/main/carbonio-ws-collaboration-openapi/src/main/resources/ws-collaboration/ws-collaboration-api.yaml