#  https://openapi-generator.tech/docs/generators/java
### POM
groupId: com.zextras.team
artifactId: community
artifactDescription: Zextras Team CE Api

developerEmail: smokybeans@zextras.com
developerOrganization: Zextras S.r.l.
developerOrganizationUrl: https://www.zextras.com

### Structure
modelPackage: com.zextras.team.model
apiPackage: com.zextras.team.api


library: resteasy
### Code
dateLibrary: java8-localdatetime