-- SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
--
-- SPDX-License-Identifier: AGPL-3.0-only

ALTER TABLE CHATS.MEETING
    ADD NAME         VARCHAR(128),
    ADD MEETING_TYPE VARCHAR(32) NOT NULL DEFAULT 'PERMANENT',
    ADD EXPIRATION   TIMESTAMP,
    ADD ACTIVE       BOOLEAN DEFAULT FALSE;

ALTER TABLE CHATS.VIDEOSERVER_SESSION
    ALTER COLUMN AUDIO_HANDLE_ID DROP NOT NULL,
    ALTER COLUMN VIDEO_HANDLE_ID DROP NOT NULL,
    ADD COLUMN VIDEOIN_HANDLE_ID  VARCHAR(64),
    ADD COLUMN SCREEN_HANDLE_ID   VARCHAR(64),
    ADD COLUMN VIDEO_IN_STREAM_ON BOOLEAN DEFAULT FALSE;

ALTER TABLE CHATS.VIDEOSERVER_SESSION
    RENAME COLUMN VIDEO_HANDLE_ID to VIDEOOUT_HANDLE_ID;

ALTER TABLE CHATS.VIDEOSERVER_SESSION
    RENAME COLUMN VIDEO_STREAM_ON to VIDEO_OUT_STREAM_ON;

