-- SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
--
-- SPDX-License-Identifier: AGPL-3.0-only

ALTER TABLE CHATS.FILE_METADATA ADD COLUMN MESSAGE_ID VARCHAR(64);
ALTER TABLE CHATS.FILE_METADATA ADD COLUMN STANZA_ID VARCHAR(64);

CREATE INDEX FILE_METADATA_MESSAGE_ID ON CHATS.FILE_METADATA (MESSAGE_ID);
CREATE INDEX FILE_METADATA_ORIGINAL_SIZE__ID ON CHATS.FILE_METADATA (ORIGINAL_SIZE, ID);
