openapi: 3.0.3
info:
  title: Zextras Carbonio Chats CE Api
  description: Zextras Carbonio Chats CE HTTP APIs definition.
  version: 0.1.1
  contact:
    email: smokybeans@zextras.com
servers:
  - url: http://localhost:10000
tags:
  - name: Consul
paths:
  /consul/kv-store:
    post:
      tags:
        - Consul
      summary: Webhook for consul properties watcher
      operationId: setConsulProperties
      requestBody:
        $ref: '#/components/requestBodies/SetConsulPropertiesRequest'
      responses:
        204:
          $ref: '#/components/responses/204SetConsulProperties'
        404:
          $ref: '#/components/responses/404NotFoundResponse'
components:
  requestBodies:
    SetConsulPropertiesRequest:
      description: consul properties list
      required: true
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ConsulProperty'
  responses:
    204SetConsulProperties:
      description: All chenged properties are updated
    404NotFoundResponse:
      description: The requested resource was not found
  schemas:
    ConsulProperty:
      type: object
      description: Consul property object
      properties:
        key:
          type: string
          description: property name
          nullable: false
        createIndex:
          type: integer
        modifyIndex:
          type: integer
        lockIndex:
          type: integer
        flags:
          type: integer
        value:
          type: string
          description: property value
          nullable: false
        session:
          type: string