services:
  carbonio-ws-collaboration-db:
    image: postgres:16-alpine
    container_name: carbonio-ws-collaboration-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: carbonio-ws-collaboration-db
      POSTGRES_USER: carbonio-ws-collaboration-db
      POSTGRES_PASSWORD: password
    volumes:
      - carbonio-ws-collaboration_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carbonio-ws-collaboration-db -d carbonio-ws-collaboration-db"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  carbonio-message-dispatcher-db:
    image: registry.dev.zextras.com/dev/carbonio-message-dispatcher-db
    container_name: carbonio-message-dispatcher-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: carbonio-message-dispatcher-db
      POSTGRES_USER: carbonio-message-dispatcher-db
      POSTGRES_PASSWORD: password
    volumes:
      - carbonio-message-dispatcher_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U carbonio-message-dispatcher-db -d carbonio-message-dispatcher-db" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  carbonio-message-broker:
    image: registry.dev.zextras.com/dev/carbonio-message-broker:latest
    container_name: carbonio-message-broker
    hostname: carbonio-message-broker
    restart: unless-stopped
    ports:
      - "10001:10001" # RabbitMQ management port
    volumes:
      - carbonio-message-broker_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  carbonio-message-dispatcher:
    image: registry.dev.zextras.com/dev/carbonio-message-dispatcher:latest
    container_name: carbonio-message-dispatcher
    hostname: carbonio-message-dispatcher
    restart: unless-stopped
    ports:
      - "10000:10000"  # HTTP port
    depends_on:
      carbonio-message-dispatcher-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mongooseimctl", "status"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 60s

  carbonio-user-management:
    image: registry.dev.zextras.com/dev/carbonio-user-management:latest
    container_name: carbonio-user-management
    restart: on-failure
    environment:
      - CARBONIO_USER_MANAGEMENT_HOST=carbonio-user-management
      - CARBONIO_USER_MANAGEMENT_PORT=10000
      - CARBONIO_MAILBOX_HOST=mailbox1
      - CARBONIO_MAILBOX_PORT=8080
    depends_on:
      mailbox1:
        condition: service_healthy

  mailbox1:
    image: registry.dev.zextras.com/dev/carbonio-mailbox:latest
    container_name: mailbox1
    depends_on:
      openldap:
        condition: service_healthy
      postfix:
        condition: service_healthy
    hostname: mailbox1.demo.zextras.io
    restart: on-failure
    volumes:
      - ./provisioning.sh:/tmp/provisioning.sh
    healthcheck:
      interval: 60s
      retries: 10
      start_period: 20s
      test: curl --fail --silent localhost:8080/service/health/ready || exit 1
      timeout: 10s

  mailbox2:
    image: registry.dev.zextras.com/dev/carbonio-mailbox:latest
    container_name: mailbox2
    depends_on:
      openldap:
        condition: service_healthy
      postfix:
        condition: service_healthy
    hostname: mailbox2.demo.zextras.io
    restart: on-failure
    volumes:
      - ./provisioning.sh:/tmp/provisioning.sh
    healthcheck:
      interval: 60s
      retries: 10
      start_period: 20s
      test: curl --fail --silent localhost:8080/service/health/ready || exit 1
      timeout: 10s

  webui:
    image: localhost:5001/web-ui:latest
    container_name: webui
    depends_on:
      - mailbox1
      - mailbox2
    ports:
      - "443:443"
      - "6071:6071"
      - "993:993"
      - "143:143"

  openldap:
    image: registry.dev.zextras.com/dev/carbonio-openldap:latest
    container_name: openldap
    restart: on-failure
    healthcheck:
      interval: 60s
      retries: 10
      start_period: 20s
      test: nc -z localhost 1389 || exit 1
      timeout: 10s

  mariadb:
    image: registry.dev.zextras.com/dev/carbonio-mariadb:latest
    container_name: mariadb

  postfix:
    image: registry.dev.zextras.com/dev/carbonio-mta:latest
    container_name: postfix
    depends_on:
      openldap:
        condition: service_healthy
    healthcheck:
      interval: 60s
      retries: 10
      start_period: 20s
      test: netcat -z localhost 25 || exit 1
      timeout: 10s

  carbonio-ws-collaboration:
    build:
      context: ..
      dockerfile: docker/wsc/Dockerfile
    container_name: carbonio-ws-collaboration
    restart: unless-stopped
    ports:
      - "5005:5005"
      - "8080:8080"
    env_file:
      - path: ../.env
    depends_on:
      carbonio-ws-collaboration-db:
        condition: service_healthy
      carbonio-message-broker:
        condition: service_healthy
      carbonio-message-dispatcher:
        condition: service_healthy
    healthcheck:
      interval: 60s
      retries: 10
      start_period: 20s
      test: curl --fail --silent localhost:8080/health || exit 1
      timeout: 10s

volumes:
  carbonio-ws-collaboration_data:
    name: carbonio_ws-collaboration_data
  carbonio-message-dispatcher_data:
    name: carbonio_message_dispatcher_data
  carbonio-message-broker_data:
    name: carbonio_message-broker_data
  mailbox1:
