services:
  carbonio-ws-collaboration-ce:
    build:
      context: ../
      dockerfile: docker/wsc/Dockerfile
      target: final
    container_name: carbonio-ws-collaboration
    hostname: docker.carbonio.localhost
    restart: unless-stopped
    networks:
      carbonio-network:
        ipv4_address: "172.28.0.22"
    ports:
      - "5005:5005"
      - "8880:8080"
      - "9010:9010" # JMX port
    env_file:
      - path: ./wsc/.env.sample
    develop:
      watch:
        - action: rebuild
          path: ../carbonio-ws-collaboration-core/src
        - action: rebuild
          path: ../carbonio-ws-collaboration-boot/src
        - action: rebuild
          path: ../carbonio-ws-collaboration-openapi/src
    healthcheck:
      interval: 60s
      retries: 10
      start_period: 20s
      test: curl --fail --silent localhost:8080/health || exit 1
      timeout: 10s

networks:
  carbonio-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
    external: true
