services:
  carbonio-ws-collaboration-ce:
    build:
      context: ../
      dockerfile: docker/wsc/Dockerfile

      target: local-dev
    networks:
      carbonio-network:
        ipv4_address: "172.28.0.22"
    ports:
      - "5005:5005"
      - "8880:8080"
      - "9010:9010" # JMX port
      - "2222:22" # SSH port
    env_file:
      - path: wsc/.env.sample
    volumes:
      - ..:/app
    tty: true
    stdin_open: true
    command: tail -f /dev/null

networks:
  carbonio-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
    external: true
