-- SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
--
-- SPDX-License-Identifier: AGPL-3.0-only

CREATE SCHEMA IF NOT EXISTS CHATS;

CREATE TABLE IF NOT EXISTS CHATS.CHATS_USER
(
    ID                 VARCHAR(64) PRIMARY KEY,
    PICTURE_UPDATED_AT TIMESTAMP,
    STATUS_MESSAGE     VARCHAR(256) DEFAULT '' NOT NULL,
    HASH               VARCHAR(256) UNIQUE     NOT NULL,
    CREATED_AT         TIMESTAMP               NOT NULL,
    UPDATED_AT         TIMESTAMP               NOT NULL
);
CREATE UNIQUE INDEX IDX_USER_HASH ON CHATS.CHATS_USER (HASH);


CREATE TABLE IF NOT EXISTS CHATS.ROOM
(
    ID                 VARCHAR(64) PRIMARY KEY,
    NAME               VARCHAR(128)        NOT NULL,
    DESCRIPTION        VARCHAR(256),
    HASH               VARCHAR(256) UNIQUE NOT NULL,
    TYPE               VARCHAR(32)         NOT NULL,
    PICTURE_UPDATED_AT TIMESTAMP,
    MEETING_ID         VARCHAR(64),
    CREATED_AT         TIMESTAMP           NOT NULL,
    UPDATED_AT         TIMESTAMP           NOT NULL
);
CREATE UNIQUE INDEX IDX_ROOM_HASH ON CHATS.ROOM (HASH);


CREATE TABLE IF NOT EXISTS CHATS.SUBSCRIPTION
(
    USER_ID    VARCHAR(64),
    ROOM_ID    VARCHAR(64),
    JOINED_AT  TIMESTAMP,
    OWNER      BOOLEAN DEFAULT FALSE,
    EXTERNAL   BOOLEAN DEFAULT FALSE,
    TEMPORARY  BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,

    PRIMARY KEY (USER_ID, ROOM_ID),
    CONSTRAINT FK_SUBSCRIPTION_ROOM__ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES CHATS.ROOM (ID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS CHATS.ROOM_USER_SETTINGS
(
    USER_ID     VARCHAR(64),
    ROOM_ID     VARCHAR(64),
    MUTED_UNTIL TIMESTAMP,
    CLEARED_AT  TIMESTAMP,
    CREATED_AT  TIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP NOT NULL,

    PRIMARY KEY (USER_ID, ROOM_ID),
    CONSTRAINT FK_ROOM_USER_SETTINGS__ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES CHATS.ROOM (ID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS CHATS.FILE_METADATA
(
    ID            VARCHAR(64) PRIMARY KEY,
    NAME          VARCHAR(256) NOT NULL,
    ORIGINAL_SIZE INT          NOT NULL,
    MIME_TYPE     VARCHAR(64)  NOT NULL,
    TYPE          VARCHAR(32)  NOT NULL,
    USER_ID       VARCHAR(64)  NOT NULL,
    ROOM_ID       VARCHAR(64),
    CREATED_AT    TIMESTAMP    NOT NULL,
    UPDATED_AT    TIMESTAMP    NOT NULL,

    CONSTRAINT FK_FILE__ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES CHATS.ROOM (ID) ON DELETE SET NULL
);
CREATE INDEX FILE_METADATA_CREATED_AT__ID ON CHATS.FILE_METADATA (CREATED_AT, ID);

CREATE TABLE IF NOT EXISTS CHATS.MEETING
(
    ID         VARCHAR(64) PRIMARY KEY,
    ROOM_ID    VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP   NOT NULL,
    CONSTRAINT FK_MEETING_ROOM__ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES CHATS.ROOM (ID) ON DELETE NO ACTION
);
ALTER TABLE CHATS.ROOM
    ADD CONSTRAINT FK_ROOM__MEETING FOREIGN KEY (MEETING_ID) REFERENCES CHATS.MEETING (ID) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS CHATS.PARTICIPANT
(
    MEETING_ID       VARCHAR(64),
    SESSION_ID       VARCHAR(64),
    USER_ID          VARCHAR(64) NOT NULL,
    AUDIO_STREAM_ON  BOOLEAN DEFAULT FALSE,
    VIDEO_STREAM_ON  BOOLEAN DEFAULT FALSE,
    SCREEN_STREAM_ON BOOLEAN DEFAULT FALSE,
    CREATED_AT       TIMESTAMP   NOT NULL,
    UPDATED_AT       TIMESTAMP   NOT NULL,
    PRIMARY KEY (MEETING_ID, SESSION_ID),
    CONSTRAINT FK_PARTICIPANT__MEETING_ID FOREIGN KEY (MEETING_ID) REFERENCES CHATS.MEETING (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CHATS.VIDEOSERVER_MEETING
(
    MEETING_ID      VARCHAR(64) PRIMARY KEY,
    CONNECTION_ID   VARCHAR(64) NOT NULL,
    AUDIO_HANDLE_ID VARCHAR(64) NOT NULL,
    VIDEO_HANDLE_ID VARCHAR(64) NOT NULL,
    AUDIO_ROOM_ID   VARCHAR(64) NOT NULL,
    VIDEO_ROOM_ID   VARCHAR(64) NOT NULL,
    CONSTRAINT FK_VS_MEETING__MEETING FOREIGN KEY (MEETING_ID) REFERENCES CHATS.MEETING (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CHATS.VIDEOSERVER_SESSION
(
    SESSION_ID       VARCHAR(64),
    MEETING_ID       VARCHAR(64),
    CONNECTION_ID    VARCHAR(64) NOT NULL,
    AUDIO_HANDLE_ID  VARCHAR(64) NOT NULL,
    VIDEO_HANDLE_ID  VARCHAR(64) NOT NULL,
    AUDIO_STREAM_ON  BOOLEAN DEFAULT FALSE,
    VIDEO_STREAM_ON  BOOLEAN DEFAULT FALSE,
    SCREEN_STREAM_ON BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (SESSION_ID, MEETING_ID),
    CONSTRAINT FK_VS_SESSION__VS_MEETING FOREIGN KEY (MEETING_ID) REFERENCES CHATS.VIDEOSERVER_MEETING (MEETING_ID) ON DELETE CASCADE
);