-- SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
--
-- SPDX-License-Identifier: AGPL-3.0-only

CREATE TABLE IF NOT EXISTS CHATS.RECORDING
(
    ID          VARCHAR(64)  PRIMARY KEY,
    MEETING_ID  VARCHAR(64)  NOT NULL,
    STARTER_ID  VARCHAR(64)  NOT NULL,
    STARTED_AT  TIMESTAMP    NOT NULL,
    TOKEN       VARCHAR(264) NOT NULL,
    STATUS      VARCHAR(32)  NOT NULL,
    CONSTRAINT FK_RECORDING__MEETING_ID FOREIGN KEY (MEETING_ID) REFERENCES CHATS.MEETING (ID) ON DELETE CASCADE
);
