-- SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
--
-- SPDX-License-Identifier: AGPL-3.0-only

ALTER TABLE CHATS.VIDEOSERVER_SESSION
    ALTER COLUMN AUDIO_HANDLE_ID DROP NOT NULL;

ALTER TABLE CHATS.VIDEOSERVER_SESSION
    ALTER COLUMN VIDEO_HANDLE_ID DROP NOT NULL;

ALTER TABLE CHATS.VIDEOSERVER_SESSION
    RENAME COLUMN VIDEO_HANDLE_ID to VIDEOOUT_HANDLE_ID;

ALTER TABLE CHATS.VIDEOSERVER_SESSION
    ADD COLUMN VIDEOIN_HANDLE_ID VARCHAR(64);

ALTER TABLE CHATS.VIDEOSERVER_SESSION
    ADD COLUMN SCREEN_HANDLE_ID VARCHAR(64);

ALTER TABLE CHATS.VIDEOSERVER_SESSION
    RENAME COLUMN VIDEO_STREAM_ON to VIDEO_OUT_STREAM_ON;

ALTER TABLE CHATS.VIDEOSERVER_SESSION
    ADD COLUMN VIDEO_IN_STREAM_ON BOOLEAN DEFAULT FALSE;
