-- SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
--
-- SPDX-License-Identifier: AGPL-3.0-only

ALTER TABLE CHATS.PARTICIPANT
    ADD COLUMN QUEUE_ID VARCHAR(64);

ALTER TABLE CHATS.PARTICIPANT
    DROP CONSTRAINT PARTICIPANT_PKEY;

ALTER TABLE CHATS.PARTICIPANT
    ADD PRIMARY KEY (MEETING_ID, USER_ID);

ALTER TABLE CHATS.PARTICIPANT
    DROP COLUMN SESSION_ID;

ALTER TABLE CHATS.VIDEOSERVER_SESSION
    ADD COLUMN USER_ID VARCHAR(64),
    ADD COLUMN QUEUE_ID VARCHAR(64);

ALTER TABLE CHATS.VIDEOSERVER_SESSION
DROP CONSTRAINT VIDEOSERVER_SESSION_PKEY;

ALTER TABLE CHATS.VIDEOSERVER_SESSION
    ADD PRIMARY KEY (MEETING_ID, USER_ID);

ALTER TABLE CHATS.VIDEOSERVER_SESSION
DROP COLUMN SESSION_ID;