-- SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
--
-- SPDX-License-Identifier: AGPL-3.0-only

CREATE INDEX PARTICIPANT_QUEUE_ID ON CHATS.PARTICIPANT (QUEUE_ID);

CREATE INDEX MEETING_ROOM_ID ON CHATS.MEETING (ROOM_ID);

CREATE INDEX FILE_METADATA_USER_ID ON CHATS.FILE_METADATA (USER_ID);
CREATE INDEX FILE_METADATA_ROOM_ID ON CHATS.FILE_METADATA (ROOM_ID);
CREATE INDEX FILE_METADATA_TYPE ON CHATS.FILE_METADATA (TYPE);

CREATE INDEX VIDEOSERVER_SESSION_CONNECTION_ID ON CHATS.VIDEOSERVER_SESSION (CONNECTION_ID);

CREATE INDEX WAITING_PARTICIPANT_MEETING_ID ON CHATS.WAITING_PARTICIPANT (MEETING_ID);
CREATE INDEX WAITING_PARTICIPANT_USER_ID ON CHATS.WAITING_PARTICIPANT (USER_ID);
CREATE INDEX WAITING_PARTICIPANT_STATUS ON CHATS.WAITING_PARTICIPANT (STATUS);
