-- SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
--
-- SPDX-License-Identifier: AGPL-3.0-only

ALTER TABLE CHATS.ROOM
DROP CONSTRAINT IF EXISTS FK_ROOM_PARENT_ID__ROOM_ID;

ALTER TABLE CHATS.ROOM
DROP COLUMN IF EXISTS PARENT_ID,
    DROP COLUMN IF EXISTS RANK;

ALTER TABLE CHATS.ROOM_USER_SETTINGS
DROP COLUMN IF EXISTS RANK;
