#!/bin/bash

# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

JAVA_HOME="/usr/share/carbonio/ws-collaboration:/opt/zextras/common/lib/jvm/java"
export JAVA_HOME
/opt/zextras/common/bin/java \
  -Djava.net.preferIPv4Stack=true \
  -Xms1024m \
  -Xmx2048m \
  -XX:+UseZGC \
  -jar /usr/share/carbonio/carbonio-ws-collaboration.jar
