#!/bin/bash

# SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

# This script add not existing behavioral configuration values in consul

CONSUL_TOKEN_PATH="/etc/carbonio/ws-collaboration/service-discover/token"

MAIN_SERVICE_NAME="carbonio-ws-collaboration"

CONFIGURATIONS=(
  "$MAIN_SERVICE_NAME/configs/can-video-call:true"
  "$MAIN_SERVICE_NAME/configs/can-use-virtual-background:true"
  "$MAIN_SERVICE_NAME/configs/can-see-message-reads:true"
  "$MAIN_SERVICE_NAME/configs/can-see-users-presence:true"
  "$MAIN_SERVICE_NAME/configs/max-user-image-size-in-kb:512"
  "$MAIN_SERVICE_NAME/configs/max-room-image-size-in-kb:512"
  "$MAIN_SERVICE_NAME/configs/edit-message-time-limit-in-minutes:10"
  "$MAIN_SERVICE_NAME/configs/delete-message-time-limit-in-minutes:10"
  "$MAIN_SERVICE_NAME/configs/max-group-members:128"
  "$MAIN_SERVICE_NAME/broker/virtual-host:/"
  "$MAIN_SERVICE_NAME/broker/requested-heartbeat-in-sec:60"
  "$MAIN_SERVICE_NAME/broker/connection-timeout-in-milli:60000"
  "$MAIN_SERVICE_NAME/broker/automatic-recovery-enabled:true"
  "$MAIN_SERVICE_NAME/broker/topology-recovery-enabled:false"
  "$MAIN_SERVICE_NAME/broker/network-recovery-interval:30000"
  "$MAIN_SERVICE_NAME/hikari/min-pool-size:10"
  "$MAIN_SERVICE_NAME/hikari/max-pool-size:10"
  "$MAIN_SERVICE_NAME/hikari/idle-timeout:10000"
  "$MAIN_SERVICE_NAME/hikari/leak-detection-threshold:5000"
  "$MAIN_SERVICE_NAME/hikari/max-lifetime:600000"
  "$MAIN_SERVICE_NAME/server/max-threads:2048"
  "$MAIN_SERVICE_NAME/server/min-threads:8"
  "$MAIN_SERVICE_NAME/server/max-queue-requests:2048"
)

get_consul_kv() {
  KEY=$1
  CONSUL_VALUE=$(consul kv get -token-file="$CONSUL_TOKEN_PATH" "${KEY}")
}

for item in "${CONFIGURATIONS[@]}"; do
  KEY=${item%%:*}

  get_consul_kv "$KEY" >/dev/null 2>&1
  CONFIG=$CONSUL_VALUE

  if [[ "$CONFIG" == "" ]]; then
    consul kv put -token-file="$CONSUL_TOKEN_PATH" "$KEY" "${item##*:}"
  fi
done
