#!/bin/bash

# SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

# This script clean up all meeting entries in meeting table

DB_SERVICE_NAME="carbonio-ws-collaboration-db"
DATABASE_NAME="${DB_SERVICE_NAME}"
DATABASE_USERNAME="${DB_SERVICE_NAME}"
CONSUL_TOKEN_PATH="/etc/carbonio/ws-collaboration-db/service-discover/token"

function syntax() {
    echo "Syntax: [PGPASSWORD=password] $0 username [host] [port]"
    exit 1
}

set -e

if [[ $(id -u) -ne 0 ]]; then
  echo "Please run as root"
  exit 1
fi

if [[ -z "$1" ]]; then
  syntax;
fi

NOT_ASK_FOR_PGPASSWORD='-w'
if [[ -z "${PGPASSWORD}" ]]; then
  NOT_ASK_FOR_PGPASSWORD=''
fi

ROOT_DB_USERNAME="$1"
POSTGRES_HOST=$2
POSTGRES_PORT=$3

if [ -z "${POSTGRES_HOST}" ]; then
  POSTGRES_HOST="localhost";
fi

if [ -z "${POSTGRES_PORT}" ]; then
  POSTGRES_PORT="5432";
fi

echo "Database: $POSTGRES_HOST:$POSTGRES_PORT user ${ROOT_DB_USERNAME}"

psql -h "${POSTGRES_HOST}" -p "${POSTGRES_PORT}" -U "${ROOT_DB_USERNAME}" -d "${DATABASE_NAME}" ${NOT_ASK_FOR_PGPASSWORD} <<EOF
DELETE FROM CHATS.MEETING;
EOF

echo "Meeting table cleaned up."
