#!/bin/bash

# SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

# This script add not existing hikari configuration values in consul

CONSUL_TOKEN_PATH="/etc/carbonio/ws-collaboration/service-discover/token"

MAIN_SERVICE_NAME="carbonio-ws-collaboration"

HIKARI_CONFIGURATIONS=(
  "$MAIN_SERVICE_NAME/hikari/min-pool-size:1"
  "$MAIN_SERVICE_NAME/hikari/max-pool-size:2"
  "$MAIN_SERVICE_NAME/hikari/idle-timeout:300"
  "$MAIN_SERVICE_NAME/hikari/leak-detection-threshold:2000"
)

get_consul_kv() {
    KEY=$1
    CONSUL_VALUE=$(consul kv get -token-file="$CONSUL_TOKEN_PATH" "${KEY}")
}

for item in "${HIKARI_CONFIGURATIONS[@]}"
do
    KEY=${item%%:*}

    get_consul_kv "$KEY" >/dev/null 2>&1; CONFIG=$CONSUL_VALUE

    if [[ "$CONFIG" == "" ]]; then
      consul kv put -token-file="$CONSUL_TOKEN_PATH" "$KEY" "${item##*:}"
    fi
done